modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="emeraldstuff"
version="1.0.0"
displayName="Emeraldanium"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BeeTheCat"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.emeraldstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration